//! Invite-code encoding for one-time pairing (ADR-0002, `docs/design/
//! protocol.md` §15, `PLAN.md` M7 Step 4).
//!
//! The invite *secret* is [`INVITE_SECRET_LEN`] (20) raw bytes — 160 bits,
//! the design value `PLAN.md` M7 §4.1 #7 fixed — generated by the caller
//! (`qsh-core`, which has the CSPRNG dependency; this crate is sans-IO and
//! owns no randomness). This module only owns the **display form**: a
//! lowercase, hyphenated Crockford Base32 string, and parsing it back.
//!
//! Crockford Base32 (<https://www.crockford.com/base32.html>) was chosen
//! over standard/RFC 4648 Base32 for the two properties a human re-typing a
//! code by hand benefits from: no padding (160 bits divides evenly into 32
//! five-bit symbols, so there is nothing to pad), and a smaller alphabet
//! that drops the letters most often confused with digits or with each
//! other (`i`, `l`, `o`, `u`), remapping the visually-ambiguous ones back
//! onto a real symbol instead of just excluding them silently:
//!
//! - `i` and `l` decode as `1`;
//! - `o` decodes as `0`;
//! - `u` is never used and is rejected outright (Crockford's own spec: kept
//!   out to avoid accidental profanity and to avoid a `v`/`u` mix-up).
//!
//! Parsing is case-insensitive and ignores `-` separators, so the display
//! form's `xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx` grouping is only a
//! rendering convenience — copy-pasting with or without the hyphens (or in
//! upper/lower/mixed case) round-trips identically.

use thiserror::Error;

/// Length of the raw invite secret in bytes: 160 bits (`PLAN.md` M7 §4.1 #7).
pub const INVITE_SECRET_LEN: usize = 20;

/// Number of Crockford Base32 symbols the display form has: `160 / 5 = 32`,
/// exactly (no padding).
pub const INVITE_CODE_SYMBOLS: usize = 32;

/// Symbols per hyphenated group in the display form (`PLAN.md` M7 §4.1 #7:
/// `xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx`, 8 groups of 4).
const GROUP_LEN: usize = 4;

/// The Crockford Base32 alphabet, lowercase, in symbol-value order (index
/// == 5-bit value). Excludes `i`, `l`, `o`, `u`.
const ALPHABET: &[u8; 32] = b"0123456789abcdefghjkmnpqrstvwxyz";

/// Encode a 160-bit invite secret as the lowercase, hyphenated display form:
/// `xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx-xxxx` (32 Crockford Base32 symbols,
/// grouped by 4).
pub fn encode_invite_code(secret: &[u8; INVITE_SECRET_LEN]) -> String {
    let symbols = encode_symbols(secret);
    let mut out = String::with_capacity(INVITE_CODE_SYMBOLS + INVITE_CODE_SYMBOLS / GROUP_LEN);
    for (i, chunk) in symbols.chunks(GROUP_LEN).enumerate() {
        if i > 0 {
            out.push('-');
        }
        for &b in chunk {
            out.push(b as char);
        }
    }
    out
}

fn encode_symbols(secret: &[u8; INVITE_SECRET_LEN]) -> [u8; INVITE_CODE_SYMBOLS] {
    let mut symbols = [0u8; INVITE_CODE_SYMBOLS];
    let mut bit_pos = 0usize;
    for sym in &mut symbols {
        let mut value = 0u8;
        for _ in 0..5 {
            let byte_idx = bit_pos / 8;
            let bit_idx = 7 - (bit_pos % 8);
            let bit = (secret[byte_idx] >> bit_idx) & 1;
            value = (value << 1) | bit;
            bit_pos += 1;
        }
        *sym = ALPHABET[value as usize];
    }
    symbols
}

/// Failure to parse an invite code's display form.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum InviteCodeParseError {
    /// A character outside the Crockford alphabet (after case-folding and
    /// stripping `-`) — includes `u`/`U`, which Crockford Base32 never uses
    /// (module docs).
    #[error("invalid character {0:?} in invite code")]
    InvalidCharacter(char),
    /// After stripping `-` and case-folding, the symbol count was not
    /// exactly [`INVITE_CODE_SYMBOLS`].
    #[error("invite code has {0} symbols, expected {INVITE_CODE_SYMBOLS}")]
    WrongLength(usize),
}

/// Parse an invite code's display form back into the raw 160-bit secret.
/// Case-insensitive; `-` separators are ignored wherever they appear (the
/// display form's own grouping is not enforced on input — only the total
/// symbol count is). Rejects immediately on the first invalid character or
/// a wrong final symbol count (module docs; `i`/`l` → `1`, `o` → `0`, `u`
/// rejected).
pub fn parse_invite_code(input: &str) -> Result<[u8; INVITE_SECRET_LEN], InviteCodeParseError> {
    let mut symbols: Vec<u8> = Vec::with_capacity(INVITE_CODE_SYMBOLS);
    for c in input.chars() {
        if c == '-' {
            continue;
        }
        let value = decode_symbol(c.to_ascii_lowercase())
            .ok_or(InviteCodeParseError::InvalidCharacter(c))?;
        symbols.push(value);
        // Report F-7: bail as soon as the count is unrecoverably wrong,
        // rather than pushing every remaining valid symbol from a
        // pathologically long input before checking the length at the end
        // — bounds the work to `O(INVITE_CODE_SYMBOLS)` instead of
        // `O(input length)`. No real risk either way (the caller is argv,
        // already bounded by the OS/shell), so this is a cheap hardening,
        // not a fix for an exploitable gap.
        if symbols.len() > INVITE_CODE_SYMBOLS {
            return Err(InviteCodeParseError::WrongLength(symbols.len()));
        }
    }
    if symbols.len() != INVITE_CODE_SYMBOLS {
        return Err(InviteCodeParseError::WrongLength(symbols.len()));
    }
    let mut out = [0u8; INVITE_SECRET_LEN];
    let mut bit_pos = 0usize;
    for value in symbols {
        for shift in (0..5).rev() {
            let bit = (value >> shift) & 1;
            let byte_idx = bit_pos / 8;
            let bit_idx = 7 - (bit_pos % 8);
            out[byte_idx] |= bit << bit_idx;
            bit_pos += 1;
        }
    }
    Ok(out)
}

/// Decode one already-lowercased character to its 5-bit Crockford value, or
/// `None` if it is not a Crockford Base32 symbol.
fn decode_symbol(c: char) -> Option<u8> {
    match c {
        '0'..='9' => Some(c as u8 - b'0'),
        'a'..='h' => Some(c as u8 - b'a' + 10),
        'i' | 'l' => Some(1),
        'j' => Some(18),
        'k' => Some(19),
        'm' => Some(20),
        'n' => Some(21),
        'o' => Some(0),
        'p'..='t' => Some(c as u8 - b'p' + 22),
        // Never used by Crockford Base32 — rejected outright, not remapped
        // (module docs).
        'u' => None,
        'v'..='z' => Some(c as u8 - b'v' + 27),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_all_zero_and_all_one_secrets() {
        for secret in [[0u8; INVITE_SECRET_LEN], [0xFFu8; INVITE_SECRET_LEN]] {
            let code = encode_invite_code(&secret);
            assert_eq!(parse_invite_code(&code).unwrap(), secret);
        }
    }

    #[test]
    fn round_trips_a_representative_secret() {
        let mut secret = [0u8; INVITE_SECRET_LEN];
        for (i, b) in secret.iter_mut().enumerate() {
            *b = (i as u8).wrapping_mul(37).wrapping_add(11);
        }
        let code = encode_invite_code(&secret);
        assert_eq!(parse_invite_code(&code).unwrap(), secret);
    }

    #[test]
    fn display_form_is_32_symbols_in_8_hyphenated_groups_of_4() {
        let secret = [0x5Au8; INVITE_SECRET_LEN];
        let code = encode_invite_code(&secret);
        let groups: Vec<&str> = code.split('-').collect();
        assert_eq!(groups.len(), 8, "{code}");
        for g in &groups {
            assert_eq!(g.len(), 4, "{code}");
        }
        assert_eq!(
            code.chars().filter(|c| *c != '-').count(),
            INVITE_CODE_SYMBOLS
        );
        assert!(
            code.chars()
                .all(|c| c == '-' || c.is_ascii_lowercase() || c.is_ascii_digit())
        );
    }

    #[test]
    fn parse_is_case_insensitive_and_hyphen_agnostic() {
        let secret = [0x3Cu8; INVITE_SECRET_LEN];
        let code = encode_invite_code(&secret);
        let upper = code.to_ascii_uppercase();
        let no_hyphens = code.replace('-', "");
        let mixed: String = code
            .chars()
            .enumerate()
            .map(|(i, c)| {
                if i % 2 == 0 {
                    c.to_ascii_uppercase()
                } else {
                    c
                }
            })
            .collect();
        for variant in [code.clone(), upper, no_hyphens, mixed] {
            assert_eq!(parse_invite_code(&variant).unwrap(), secret, "{variant}");
        }
    }

    #[test]
    fn ambiguous_characters_remap_as_documented() {
        // i/l -> 1, o -> 0: build two codes that differ only in an i/l/o
        // position and its "canonical" digit equivalent, and check they
        // decode identically.
        let base = encode_invite_code(&[0u8; INVITE_SECRET_LEN]);
        // The all-zero secret's first symbol is '0'; swap it for 'o'/'O'
        // and confirm it still parses to the same secret.
        assert_eq!(&base[..1], "0");
        let swapped_o = format!("o{}", &base[1..]);
        assert_eq!(
            parse_invite_code(&swapped_o).unwrap(),
            [0u8; INVITE_SECRET_LEN]
        );
        let swapped_upper_o = format!("O{}", &base[1..]);
        assert_eq!(
            parse_invite_code(&swapped_upper_o).unwrap(),
            [0u8; INVITE_SECRET_LEN]
        );

        // A secret whose first symbol is '1' (value 1): 'i' and 'l' must
        // both decode the same as a literal '1' there.
        let mut one_secret = [0u8; INVITE_SECRET_LEN];
        one_secret[0] = 0b0000_1000; // top 5 bits = 00001 = symbol value 1
        let one_code = encode_invite_code(&one_secret);
        assert_eq!(&one_code[..1], "1");
        for repl in ['i', 'I', 'l', 'L'] {
            let variant = format!("{repl}{}", &one_code[1..]);
            assert_eq!(parse_invite_code(&variant).unwrap(), one_secret, "{repl}");
        }
    }

    #[test]
    fn u_is_rejected_outright_not_remapped() {
        let base = encode_invite_code(&[0u8; INVITE_SECRET_LEN]);
        let with_u = format!("u{}", &base[1..]);
        assert_eq!(
            parse_invite_code(&with_u),
            Err(InviteCodeParseError::InvalidCharacter('u'))
        );
        let with_upper_u = format!("U{}", &base[1..]);
        assert_eq!(
            parse_invite_code(&with_upper_u),
            Err(InviteCodeParseError::InvalidCharacter('U'))
        );
    }

    #[test]
    fn rejects_wrong_length() {
        assert_eq!(
            parse_invite_code("0000-0000"),
            Err(InviteCodeParseError::WrongLength(8))
        );
        assert_eq!(
            parse_invite_code(""),
            Err(InviteCodeParseError::WrongLength(0))
        );
    }

    /// Report F-7: an over-length input bails as soon as the running
    /// symbol count exceeds [`INVITE_CODE_SYMBOLS`], instead of pushing
    /// every remaining valid symbol first and only checking the length at
    /// the end — bounds the work to `O(INVITE_CODE_SYMBOLS)`. Pins the
    /// early-bail count (`INVITE_CODE_SYMBOLS + 1`, not the full input
    /// length) so a regression back to full-scan behavior is visible here
    /// even though no caller depends on the exact number in a
    /// pathologically long `WrongLength`.
    #[test]
    fn rejects_an_overlong_input_without_scanning_all_of_it() {
        let overlong = "0".repeat(100_000);
        assert_eq!(
            parse_invite_code(&overlong),
            Err(InviteCodeParseError::WrongLength(INVITE_CODE_SYMBOLS + 1))
        );
    }

    #[test]
    fn rejects_invalid_alphabet_characters() {
        let base = encode_invite_code(&[0u8; INVITE_SECRET_LEN]);
        let with_bang = format!("!{}", &base[1..]);
        assert_eq!(
            parse_invite_code(&with_bang),
            Err(InviteCodeParseError::InvalidCharacter('!'))
        );
    }

    #[test]
    fn distinct_secrets_encode_to_distinct_codes() {
        let a = encode_invite_code(&[1u8; INVITE_SECRET_LEN]);
        let b = encode_invite_code(&[2u8; INVITE_SECRET_LEN]);
        assert_ne!(a, b);
    }
}
