//! `acl.toml` loader (`docs/design/architecture.md` §6, §7; `PLAN.md` M5
//! Step 2). Turns the file at `<config_dir>/acl.toml` into a [`Policy`] —
//! or explains, structurally, why it couldn't.
//!
//! **This deliberately does not follow [`crate::config::Config::load`] /
//! [`crate::trust::TrustStore::load`]'s "missing file → default" idiom.**
//! Those types' defaults are safe because "no config" and "no pins" both
//! mean "behave as before". An absent `acl.toml` has no such reading —
//! `docs/design/architecture.md` §6 and `PLAN.md` M5 §4.1 #1 are explicit
//! that it means "nobody has been granted anything yet", so [`PolicyLoad`]
//! gives every non-[`PolicyLoad::Loaded`] outcome an effective policy of
//! deny-all rather than quietly reusing `Config`'s pattern.
//!
//! **No partial load.** One malformed rule invalidates the whole file
//! ([`PolicyLoad::Invalid`]) — a half-applied policy would enforce
//! something the operator never wrote down and never reviewed.
//!
//! [`load_or_deny`] is `PLAN.md` M5 Step 6's production wiring: the one
//! function `crate::serve::host_runtime` and
//! `crate::reverse::listen::run_listen_unix` both call to turn this
//! module's [`PolicyLoad`] into a real [`super::Authorizer`], falling back
//! to [`super::DenyAll`] (plus a [`StartupDiagnostic`] the caller must
//! surface) on anything short of [`PolicyLoad::Loaded`]. Everything above
//! it — [`PolicySource`] itself and [`super::policy`] — was, and remains,
//! fully exercisable (including property tests) on its own.

use std::fs::File;
use std::io::{self, Read};
use std::path::{Path, PathBuf};
use std::sync::Arc;

use qsh_proto::ErrorCode;
use qsh_transport::AuthPath;
use serde::Deserialize;

use crate::config::Paths;
use crate::ops::OpError;
use crate::trust::TrustStore;

use super::policy::FamilyPrefix;
use super::{Action, ActionPattern, Authorizer, DenyAll, Policy, Rule, Scope};

/// Hard caps on `acl.toml` shape, enforced before any rule is evaluated.
/// `acl.toml` is operator-authored, not adversarial input (`PLAN.md` M5
/// §4 risk list), but "no unbounded parsing" is a hard invariant
/// regardless (`CLAUDE.md` "unbounded input rejected"). `Policy::decide`
/// is `O(rules)` per request, so bounding rule count bounds every future
/// request's ACL cost too.
///
/// Chosen generously above any real deployment's shape (a few dozen
/// principals with a handful of rules each) and far below "this file is
/// corrupted or was generated by a bug":
mod caps {
    /// A file this large already indicates corruption, not a legitimate
    /// policy — a rule is on the order of a hundred bytes at most, so
    /// even a few thousand rules fit in tens of kilobytes.
    pub(super) const MAX_FILE_BYTES: u64 = 1 << 20; // 1 MiB
    /// Far beyond any real principal/rule count QSH's target deployments
    /// (personal machines, small teams) could plausibly need.
    pub(super) const MAX_RULES: usize = 1024;
    /// `Action::ALL` has 11 entries today; this leaves headroom for the
    /// vocabulary to grow several times over without a legitimate rule
    /// ever approaching the cap.
    pub(super) const MAX_PATTERNS_PER_RULE: usize = 64;
    /// Longest legitimate value today is `fp:sha256:` + 44 base64 chars
    /// (~54 bytes); this leaves ample headroom.
    pub(super) const MAX_PRINCIPAL_LEN: usize = 256;
    /// Longest legitimate action string today is `session.control` (16
    /// bytes); longest legitimate pattern is a family wildcard like
    /// `session.*` (10 bytes).
    pub(super) const MAX_PATTERN_LEN: usize = 128;
}

/// The outcome of loading `acl.toml`. Three states, deliberately explicit
/// and mutually exclusive (see module docs for why this doesn't follow
/// `Config::load`'s "missing → default" idiom).
#[derive(Debug)]
pub enum PolicyLoad {
    /// The file existed, parsed, and every rule validated.
    Loaded(Policy),
    /// No file at this path. Effective policy: deny-all.
    Missing,
    /// The file existed but could not become a policy — malformed TOML,
    /// an action pattern matching nothing in [`Action::ALL`], a value
    /// outside this module's caps, or another shape violation. Effective
    /// policy: deny-all. The [`OpError`] is `CONFIG_ERROR` and is for the
    /// operator only — `PLAN.md` M5 §4.1 #4: it must never reach a remote
    /// peer, who always sees a uniform `PERMISSION_DENIED` instead.
    Invalid(OpError),
}

impl PolicyLoad {
    /// The loaded policy, when this is [`PolicyLoad::Loaded`].
    pub fn as_loaded(&self) -> Option<&Policy> {
        match self {
            PolicyLoad::Loaded(policy) => Some(policy),
            PolicyLoad::Missing | PolicyLoad::Invalid(_) => None,
        }
    }
}

/// Loads `acl.toml`. Process-start-once by design (`PLAN.md` M5 §4.1 #6:
/// no hot reload, no lazy load — a lazily-loaded policy has a
/// "can't-decide-yet" window, and fail-open in that window would break
/// the "no resource before authorization" invariant that has held since
/// M1).
pub struct PolicySource;

impl PolicySource {
    /// Load the policy at `paths.acl_file()`.
    pub fn load(paths: &Paths) -> PolicyLoad {
        Self::load_path(&paths.acl_file())
    }

    fn load_path(path: &Path) -> PolicyLoad {
        let mut file = match File::open(path) {
            Ok(file) => file,
            Err(err) if err.kind() == io::ErrorKind::NotFound => return PolicyLoad::Missing,
            Err(err) => return PolicyLoad::Invalid(read_error(path, &err)),
        };
        // Arbitrated (`PLAN.md` M5 Step 6): warn, never deny, on a
        // group-/world-writable `acl.toml`. Denying would turn a permissions
        // slip into a second way to lock an operator out mid-incident —
        // exactly the moment they most need `acl.toml` to still load.
        // Staying silent would hide a real local risk instead: any other
        // uid on this host with write access to the file this process
        // trusts can grant itself anything the policy is capable of
        // granting. Non-fatal and independent of whether the file goes on
        // to parse — fires whenever the file exists, on every load
        // outcome. Windows ACL checking is an explicit non-goal: Windows'
        // permission model has no analogue to the unix rwx bits this reads,
        // and `docs/ROADMAP.md` already defers the Windows host role to P2.
        #[cfg(unix)]
        warn_if_group_or_world_writable(path, &file);
        // Cheap early-out on a regular file's reported size. This is NOT
        // the enforcement boundary (F2, M5 Step 2 adversarial review): a
        // FIFO, a symlink to `/dev/zero`, or any other path whose `stat`
        // size doesn't predict how many bytes reading it actually
        // produces would defeat a stat-only cap. The bounded read below
        // is what actually stops unbounded input; this is only here so
        // an ordinary huge file is rejected without reading any of it.
        if let Ok(metadata) = file.metadata()
            && metadata.len() > caps::MAX_FILE_BYTES
        {
            return PolicyLoad::Invalid(over_cap_error_with_len(path, metadata.len()));
        }
        // The real enforcement: never read more than MAX_FILE_BYTES + 1
        // bytes, regardless of what (or whether) `stat` claimed. Reading
        // one byte past the cap — rather than exactly at it — is what
        // lets the check below tell "exactly at the cap" (loads) apart
        // from "over the cap" (Invalid) without trusting any reported
        // length.
        let mut buf = Vec::new();
        if let Err(err) = (&mut file)
            .take(caps::MAX_FILE_BYTES + 1)
            .read_to_end(&mut buf)
        {
            return PolicyLoad::Invalid(read_error(path, &err));
        }
        if buf.len() as u64 > caps::MAX_FILE_BYTES {
            return PolicyLoad::Invalid(over_cap_error(path));
        }
        // UTF-8 conversion happens only after the byte-count gate above:
        // a multi-byte codepoint split by the cap+1 read boundary of an
        // over-cap file must surface as the same "over the load limit"
        // Invalid every other over-cap file gets, never a spurious
        // "invalid UTF-8" in its place.
        let text = match String::from_utf8(buf) {
            Ok(text) => text,
            Err(_) => {
                return PolicyLoad::Invalid(
                    OpError::new(
                        ErrorCode::ConfigError,
                        format!("acl.toml at {} is not valid UTF-8", path.display()),
                    )
                    .with_retryable(false),
                );
            }
        };
        match parse(&text) {
            Ok(policy) => {
                if policy.rules.is_empty() {
                    // F7: `acl = []` and a mistyped table name (e.g.
                    // `[[acls]]`, tolerated per `docs/CLI.md` §2.3's
                    // unknown-key rule) both land here indistinguishably
                    // from a deliberately empty policy — total, silent
                    // lockout otherwise, unlike `Missing`/`Invalid`.
                    tracing::warn!(
                        target: "qsh::acl",
                        "acl.toml loaded with 0 rules; every request will be denied"
                    );
                }
                PolicyLoad::Loaded(policy)
            }
            Err(message) => PolicyLoad::Invalid(
                OpError::new(
                    ErrorCode::ConfigError,
                    format!("invalid policy file {}: {message}", path.display()),
                )
                .with_retryable(false),
            ),
        }
    }
}

/// Unix half of the group-/world-writable warning installed in
/// [`PolicySource::load_path`] — see that call site's comment for the
/// warn-not-deny rationale. `tracing::warn!`, same target and structural-
/// fields-only discipline as this module's other two diagnostics (F1/F7,
/// the `capture` test helper below exercises both).
#[cfg(unix)]
fn warn_if_group_or_world_writable(path: &Path, file: &File) {
    use std::os::unix::fs::PermissionsExt;
    let Ok(metadata) = file.metadata() else {
        return;
    };
    let mode = metadata.permissions().mode() & 0o777;
    if mode & 0o022 != 0 {
        tracing::warn!(
            target: "qsh::acl",
            path = %path.display(),
            mode = format!("{mode:03o}"),
            "acl.toml is group- or world-writable; anyone else with write access to this file \
             can grant themselves anything this policy is capable of granting"
        );
    }
}

/// Machine-stable code word for [`PolicyLoad::Missing`]'s startup
/// diagnostic ([`load_or_deny`]) — distinct from [`ACL_POLICY_INVALID_CODE`]
/// so an operator (or a script watching stderr) can tell "never configured"
/// apart from "configured wrong" at a glance, the same way `doctor.rs`'s
/// `DiagnosticId` variants stay distinct. Not a [`qsh_proto::ErrorCode`]:
/// both states already carry [`ErrorCode::ConfigError`] on the operator-
/// facing side ([`PolicyLoad::Invalid`]'s own doc) — this is a second,
/// finer axis for the human-facing startup banner only, never sent to a
/// peer (a remote peer only ever sees the uniform `PERMISSION_DENIED`,
/// `PLAN.md` M5 §4.1 #4).
pub const ACL_POLICY_MISSING_CODE: &str = "acl_policy_missing";

/// Machine-stable code word for [`PolicyLoad::Invalid`]'s startup
/// diagnostic. See [`ACL_POLICY_MISSING_CODE`].
pub const ACL_POLICY_INVALID_CODE: &str = "acl_policy_invalid";

/// [`StartupDiagnostic::render`]'s headline fragment (F4, `PLAN.md` M5
/// Step 6 PR 6a adversarial ②) — pulled out to a named const, rather than
/// inlined in the `format!` below, so `crates/qsh-core/tests/acl_docs.rs`
/// can pin it against `README.md`/`docs/CLI.md` byte-for-byte
/// (`doctor.rs`'s `CONTROLLER_UNREACHABLE` precedent: the wording's one
/// source of truth is code, and the docs are gated to match it, not the
/// other way around).
pub const ACL_STARTUP_HEADLINE: &str = "no usable acl.toml policy";

/// [`StartupDiagnostic::render`]'s "nothing is granted yet" clause. See
/// [`ACL_STARTUP_HEADLINE`].
pub const ACL_STARTUP_DENIED_CLAUSE: &str = "every request is denied until this is fixed";

/// [`StartupDiagnostic::render`]'s no-auto-generation sentence. See
/// [`ACL_STARTUP_HEADLINE`].
pub const ACL_STARTUP_NO_AUTOGEN: &str = "acl.toml is never auto-generated — create it by hand";

/// [`StartupDiagnostic::render`]'s closing hint: how to verify a fix
/// *before* restarting (`PLAN.md` M5 §4.1 #1(c)'s migration-story
/// obligation, closed by M5 Step 7's `qsh acl check` — same evaluator as
/// enforcement, `docs/CLI.md` §6.15). See [`ACL_STARTUP_HEADLINE`].
pub const ACL_STARTUP_CHECK_HINT: &str = "verify a fix before restarting: qsh acl check";

/// The exactly-once, operator-facing startup banner `PLAN.md` M5 Step 6
/// requires whenever `acl.toml` did not produce a usable [`Policy`] —
/// [`PolicyLoad::Missing`] or [`PolicyLoad::Invalid`]. [`load_or_deny`]
/// composes this; `qsh-cli` prints [`StartupDiagnostic::render`]'s output
/// verbatim, once, and holds no ACL logic of its own (`CLAUDE.md`'s crate
/// boundary: renderers carry zero auth/ACL logic).
///
/// Deliberately not `crate::doctor::Diagnostic`'s all-`&'static str` shape:
/// this diagnostic's content is inherently dynamic — the exact `acl.toml`
/// path this process resolved, and (`Invalid` only) the load error's
/// line-number-only detail, reusing [`OpError::message`] rather than
/// composing a second copy of it (this crate's F1 discipline: never a
/// second, possibly-drifted no-content-echo implementation).
#[derive(Debug, Clone)]
pub struct StartupDiagnostic {
    /// [`ACL_POLICY_MISSING_CODE`] or [`ACL_POLICY_INVALID_CODE`].
    pub code: &'static str,
    /// The exact path this process looked at (`paths.acl_file()`).
    pub path: PathBuf,
    /// [`PolicyLoad::Invalid`]'s line-number-only detail. Never dumps raw
    /// source lines from the file; the only echo is a bounded (<=128-byte,
    /// single-line-escaped) grammar token from the offending rule (unknown
    /// action pattern / `auth_path` / scope — the deliberate Step 2
    /// carve-out `parse_rule` documents at its three `unknown ... {other:?}`
    /// arms). `None` for [`PolicyLoad::Missing`], which has nothing to
    /// explain beyond "the file does not exist".
    pub detail: Option<String>,
    /// A copy-pasteable minimal `acl.toml` body, pre-filled with this
    /// machine's actual pinned peer names from the trust store when it has
    /// any (`PLAN.md` M5 §4.2: local information, stderr only, never sent
    /// to a peer).
    pub example: String,
}

impl StartupDiagnostic {
    /// Compose the full stderr banner as one string. `qsh-cli` prints this
    /// verbatim — never re-derives, paraphrases, or partially prints it, so
    /// "exactly once" holds without a second source of truth that could
    /// drift from this one.
    pub fn render(&self) -> String {
        let mut out = format!(
            "{ACL_STARTUP_HEADLINE} ({}); {ACL_STARTUP_DENIED_CLAUSE}\n\
             acl.toml path: {}\n\
             error code: {}",
            self.code,
            self.path.display(),
            ErrorCode::ConfigError.as_str(),
        );
        if let Some(detail) = &self.detail {
            out.push_str(&format!("\ndetail: {detail}"));
        }
        out.push_str(&format!(
            "\n{ACL_STARTUP_NO_AUTOGEN}. minimal example:\n{}",
            self.example
        ));
        out.push('\n');
        out.push_str(ACL_STARTUP_CHECK_HINT);
        out
    }
}

/// Load `acl.toml` and turn the result straight into an [`Authorizer`] for
/// a production call site (`PLAN.md` M5 Step 6 — the only two callers are
/// `crate::serve::host_runtime` and `crate::reverse::listen::run_listen_unix`'s
/// controller side). [`PolicyLoad::Loaded`] becomes the real [`Policy`];
/// every other outcome becomes [`DenyAll`] plus a [`StartupDiagnostic`] the
/// caller must surface exactly once — fail-closed, never silent
/// (`docs/design/architecture.md` §6: "오류 시 개방은 존재하지 않는다").
///
/// Reads `paths.trust_file()` independently of any trust handle the caller
/// may already hold (and may already have moved into `Listener::bind` by
/// the time this runs) — tolerant of a trust-store load failure via
/// `unwrap_or_default()`, since a broken `trust.toml` is a different,
/// already-reported failure elsewhere and must not blank out this
/// diagnostic's own message.
pub fn load_or_deny(paths: &Paths) -> (Arc<dyn Authorizer>, Option<StartupDiagnostic>) {
    match PolicySource::load(paths) {
        PolicyLoad::Loaded(policy) => (Arc::new(policy), None),
        PolicyLoad::Missing => (
            Arc::new(DenyAll),
            Some(StartupDiagnostic {
                code: ACL_POLICY_MISSING_CODE,
                path: paths.acl_file(),
                detail: None,
                example: minimal_policy_example(paths),
            }),
        ),
        PolicyLoad::Invalid(err) => (
            Arc::new(DenyAll),
            Some(StartupDiagnostic {
                code: ACL_POLICY_INVALID_CODE,
                path: paths.acl_file(),
                detail: Some(err.message),
                example: minimal_policy_example(paths),
            }),
        ),
    }
}

/// Build the copy-pasteable minimal-policy example embedded in
/// [`StartupDiagnostic::render`]: one `[[acl]]` block per pinned peer in
/// `paths.trust_file()` (`PLAN.md` M5 §4.2: fill the machine's actual
/// pinned peer names in), or a single generic placeholder row when the
/// trust store has no pins yet (a fresh install before the first `qsh
/// trust add`).
fn minimal_policy_example(paths: &Paths) -> String {
    const EXAMPLE_ALLOW: &str = "[\"exec.run\", \"session.open\", \"session.list\", \"session.attach\", \"session.control\"]";
    let names: Vec<String> = TrustStore::load(&paths.trust_file())
        .unwrap_or_default()
        .peers()
        .iter()
        .map(|peer| peer.name.clone())
        .collect();
    if names.is_empty() {
        return format!("[[acl]]\nprincipal = \"device:<name>\"\nallow = {EXAMPLE_ALLOW}\n");
    }
    let mut out = String::new();
    for name in names {
        out.push_str(&format!(
            "[[acl]]\nprincipal = \"device:{name}\"\nallow = {EXAMPLE_ALLOW}\n"
        ));
    }
    out
}

fn read_error(path: &Path, err: &io::Error) -> OpError {
    OpError::new(
        ErrorCode::ConfigError,
        format!("failed to read {}: {err}", path.display()),
    )
    .with_retryable(false)
}

/// Over-cap error carrying the real reported length (the stat-based
/// early-out, which actually knows it).
fn over_cap_error_with_len(path: &Path, len: u64) -> OpError {
    OpError::new(
        ErrorCode::ConfigError,
        format!(
            "acl.toml at {} is {} bytes, over the {}-byte load limit",
            path.display(),
            len,
            caps::MAX_FILE_BYTES
        ),
    )
    .with_retryable(false)
}

/// Over-cap error from the bounded-read boundary, which only knows the
/// file is over the cap — not its real total length (only
/// `MAX_FILE_BYTES + 1` bytes were ever read).
fn over_cap_error(path: &Path) -> OpError {
    OpError::new(
        ErrorCode::ConfigError,
        format!(
            "acl.toml at {} exceeds the {}-byte load limit",
            path.display(),
            caps::MAX_FILE_BYTES
        ),
    )
    .with_retryable(false)
}

/// Raw `acl.toml` shape before validation. No `deny_unknown_fields`: an
/// unrecognized key is ignored, not a load error (`docs/CLI.md` §2.3).
#[derive(Debug, Default, Deserialize)]
struct RawFile {
    #[serde(default)]
    acl: Vec<RawRule>,
}

#[derive(Debug, Deserialize)]
struct RawRule {
    principal: String,
    #[serde(default)]
    auth_path: Option<String>,
    allow: Vec<String>,
    #[serde(default)]
    scope: Option<String>,
}

/// A fixed, single-line reason for a `toml::de::Error` — never
/// `err.to_string()`/`{err}` verbatim (F1, M5 Step 2 adversarial review):
/// `toml::de::Error`'s `Display` renders the offending source line, which
/// for `acl.toml` can be — and in the wild plausibly will be — a
/// principal string, so the raw message is a payload leak straight into
/// an operator-facing `CONFIG_ERROR` (`CLAUDE.md`: audit/diagnostic
/// output is structural, never payload). Only the line number, computed
/// from the error's byte span, survives into the message.
fn toml_error_message(err: &toml::de::Error, text: &str) -> String {
    match err.span() {
        Some(span) => {
            let offset = span.start.min(text.len());
            let line = text.as_bytes()[..offset]
                .iter()
                .filter(|&&b| b == b'\n')
                .count()
                + 1;
            format!("parse error at line {line}")
        }
        None => "parse error".to_string(),
    }
}

fn parse(text: &str) -> Result<Policy, String> {
    let raw: RawFile = toml::from_str(text).map_err(|err| toml_error_message(&err, text))?;
    if raw.acl.len() > caps::MAX_RULES {
        return Err(format!(
            "{} rules exceeds the {}-rule load limit",
            raw.acl.len(),
            caps::MAX_RULES
        ));
    }
    let rules = raw
        .acl
        .into_iter()
        .enumerate()
        .map(|(index, raw_rule)| parse_rule(index, raw_rule))
        .collect::<Result<Vec<Rule>, String>>()?;
    Ok(Policy { rules })
}

fn parse_rule(index: usize, raw: RawRule) -> Result<Rule, String> {
    if raw.principal.is_empty() {
        return Err(format!("rule {index}: principal must not be empty"));
    }
    if raw.principal.len() > caps::MAX_PRINCIPAL_LEN {
        return Err(format!(
            "rule {index}: principal exceeds {} bytes",
            caps::MAX_PRINCIPAL_LEN
        ));
    }
    // F6(b): reject anything that isn't one of `docs/CLI.md` §6.15's
    // three principal shapes — `user:`/`device:`/`fp:sha256:` — at load
    // time, rather than silently accepting a rule that can never match
    // any real `Principal::to_string()` output (`docs/CLI.md` §6.15's
    // own `acl check --principal` validation, mirrored here). The
    // principal value itself is never echoed (F1 discipline: it may be
    // exactly the kind of thing an operator doesn't want in a log line).
    if !has_valid_principal_shape(&raw.principal) {
        return Err(format!("rule {index}: invalid principal shape"));
    }
    let auth_path = match raw.auth_path.as_deref() {
        None => AuthPath::Pin,
        Some("pin") => AuthPath::Pin,
        Some("ca") => AuthPath::Ca,
        Some(other) => {
            return Err(format!(
                "rule {index}: unknown auth_path {other:?}, expected \"pin\" or \"ca\""
            ));
        }
    };
    if raw.allow.is_empty() {
        return Err(format!("rule {index}: allow must not be empty"));
    }
    if raw.allow.len() > caps::MAX_PATTERNS_PER_RULE {
        return Err(format!(
            "rule {index}: {} action patterns exceeds the {}-pattern limit",
            raw.allow.len(),
            caps::MAX_PATTERNS_PER_RULE
        ));
    }
    let mut allow = Vec::with_capacity(raw.allow.len());
    for pattern in &raw.allow {
        if pattern.len() > caps::MAX_PATTERN_LEN {
            // F1 (`PLAN.md` M5 Step 6 PR 6a adversarial ①): unlike the
            // three deliberate Step 2 grammar-token echoes below (unknown
            // action pattern/auth_path/scope — bounded to <=128 bytes by
            // construction, since that is exactly the cap those shapes
            // pass), an over-length pattern has no such bound: it can be
            // anything up to the 1MiB file cap. Report only its byte
            // length and the rule index — never the content itself.
            return Err(format!(
                "rule {index}: action pattern of {} bytes exceeds {} bytes",
                pattern.len(),
                caps::MAX_PATTERN_LEN
            ));
        }
        let parsed = parse_action_pattern(pattern)
            .ok_or_else(|| format!("rule {index}: unknown action pattern {pattern:?}"))?;
        // A rule explicitly naming an always-denied action loads (it is
        // not a grammar error — the action exists), but it can never be
        // granted (`Action::is_always_denied`, checked ahead of every
        // rule by `Policy::decide`) — that mismatch between what the file
        // says and what it can ever do is worth one operator-facing
        // warning line, not silence (`PLAN.md` M5 Step 2 (a)). Wildcard
        // patterns that merely *also* cover an always-denied action
        // (`forward.*`) do not warn — only a pattern that names the
        // always-denied action exactly.
        if let ActionPattern::Exact(action) = parsed
            && action.is_always_denied()
        {
            tracing::warn!(
                target: "qsh::acl",
                rule = index,
                action = action.as_str(),
                "acl.toml rule names an always-denied action; it can never be granted"
            );
        }
        allow.push(parsed);
    }
    let scope = match raw.scope.as_deref() {
        None => Scope::Owned,
        Some("owned") => Scope::Owned,
        Some("any") => Scope::Any,
        Some(other) => {
            return Err(format!(
                "rule {index}: unknown scope {other:?}, expected \"owned\" or \"any\""
            ));
        }
    };
    Ok(Rule {
        principal: raw.principal,
        auth_path,
        allow,
        scope,
    })
}

/// Parse one `allow` entry: an exact match against [`Action::ALL`], or a
/// trailing-`.*` family wildcard that matches at least one action
/// (`docs/design/architecture.md` §6: "정확 일치 또는 trailing `.*`
/// wildcard만"). Anything else — no dot boundary (`"session*"`), a
/// leading or interior glob (`"*.run"`, `"se*.run"`), or a pattern that
/// matches nothing in [`Action::ALL`] — is `None`, which the caller turns
/// into a whole-file `CONFIG_ERROR`.
fn parse_action_pattern(raw: &str) -> Option<ActionPattern> {
    if let Some(prefix) = raw.strip_suffix(".*") {
        if prefix.is_empty() {
            return None;
        }
        for action in Action::ALL {
            let full = action.as_str();
            if let Some(dot) = full.find('.')
                && &full[..dot] == prefix
            {
                return Some(ActionPattern::Prefix(FamilyPrefix::new(&full[..=dot])));
            }
        }
        None
    } else {
        Action::ALL
            .into_iter()
            .find(|action| action.as_str() == raw)
            .map(ActionPattern::Exact)
    }
}

/// The three principal shapes `docs/CLI.md` §6.15's `acl check
/// --principal` validation mandates: `user:<name>`, `device:<name>`, or
/// `fp:sha256:<base64>` (`qsh_transport::identity::Principal`'s `Display`
/// impl — the fingerprint half is `sha256:` + base64, never hex, despite
/// what `docs/CLI.md` used to say before F6(a)'s correction). Shape only
/// — prefix plus a non-empty remainder — not a full re-validation of the
/// name/fingerprint grammar those prefixes carry (F6(b)).
fn has_valid_principal_shape(principal: &str) -> bool {
    const SHAPES: [&str; 3] = ["user:", "device:", "fp:sha256:"];
    SHAPES.iter().any(|prefix| {
        principal
            .strip_prefix(prefix)
            .is_some_and(|rest| !rest.is_empty())
    })
}

#[cfg(test)]
mod tests {
    use qsh_transport::{AuthPath, Principal};

    use super::*;
    use crate::acl::{Decision, ResourceRef};

    fn paths_with(dir: &std::path::Path) -> Paths {
        Paths::new(dir, dir)
    }

    fn write_acl(dir: &std::path::Path, text: &str) {
        std::fs::write(dir.join("acl.toml"), text).unwrap();
    }

    #[test]
    fn absent_file_is_missing_with_effective_deny_all() {
        let dir = tempfile::tempdir().unwrap();
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Missing));
        assert!(load.as_loaded().is_none());
    }

    #[test]
    fn broken_toml_is_invalid_config_error() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(dir.path(), "this is not [ valid toml");
        let load = PolicySource::load(&paths_with(dir.path()));
        match load {
            PolicyLoad::Invalid(err) => assert_eq!(err.code, ErrorCode::ConfigError),
            other => panic!("expected Invalid, got {other:?}"),
        }
    }

    #[test]
    fn unknown_action_pattern_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"bogus.action\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        match load {
            PolicyLoad::Invalid(err) => assert_eq!(err.code, ErrorCode::ConfigError),
            other => panic!("expected Invalid, got {other:?}"),
        }
    }

    #[test]
    fn dot_boundary_is_required_session_star_without_dot_is_rejected() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"session*\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(
            matches!(load, PolicyLoad::Invalid(_)),
            "\"session*\" has no dot boundary and must not parse as a wildcard"
        );
    }

    #[test]
    fn unknown_keys_are_ignored() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "future_top_level_key = 1\n\n[[acl]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\nfuture_row_key = \"x\"\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load
            .as_loaded()
            .expect("unknown keys must not fail the load");
        assert_eq!(policy.rules.len(), 1);
    }

    #[test]
    fn empty_acl_array_loads_with_all_deny() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(dir.path(), "# no rules yet\n");
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load.as_loaded().expect("an existing, empty file loads");
        assert!(policy.rules.is_empty());
        let verdict = policy.decide(
            &Principal::Device("laptop".into()),
            AuthPath::Pin,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Deny);
        assert_eq!(verdict.rule, None);
    }

    #[test]
    fn explicit_acl_array_key_but_zero_entries_also_loads_with_all_deny() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(dir.path(), "acl = []\n");
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load.as_loaded().expect("loads");
        assert!(policy.rules.is_empty());
    }

    #[test]
    fn a_rule_naming_an_always_denied_action_exactly_still_loads() {
        // PLAN.md M5 Step 2 (a): not a CONFIG_ERROR — `forward.socks` is a
        // real action name, just one no policy can ever grant. The
        // operator warning is emitted via `tracing`, not asserted here
        // (no subscriber is installed in this unit test).
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"forward.socks\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load
            .as_loaded()
            .expect("a real action name is not a grammar error");
        assert_eq!(policy.rules.len(), 1);
        // And it still can never be granted (the always-deny gate runs
        // ahead of rule matching in `Policy::decide`).
        let verdict = policy.decide(
            &Principal::User("dave".into()),
            AuthPath::Pin,
            Action::ForwardSocks,
            ResourceRef::unowned("x"),
        );
        assert_eq!(verdict.decision, Decision::Deny);
        assert_eq!(verdict.rule, None);
    }

    #[test]
    fn auth_path_and_scope_round_trip() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nauth_path = \"ca\"\nscope = \"any\"\nallow = [\"session.open\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load.as_loaded().unwrap();
        assert_eq!(policy.rules[0].auth_path, AuthPath::Ca);
        assert_eq!(policy.rules[0].scope, crate::acl::Scope::Any);
    }

    #[test]
    fn auth_path_defaults_to_pin_when_omitted() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"session.open\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load.as_loaded().unwrap();
        assert_eq!(policy.rules[0].auth_path, AuthPath::Pin);
    }

    #[test]
    fn scope_defaults_to_owned_when_omitted() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"session.open\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        let policy = load.as_loaded().unwrap();
        assert_eq!(policy.rules[0].scope, crate::acl::Scope::Owned);
    }

    #[test]
    fn unknown_auth_path_value_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nauth_path = \"bogus\"\nallow = [\"exec.run\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn unknown_scope_value_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nscope = \"bogus\"\nallow = [\"exec.run\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn empty_principal_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"\"\nallow = [\"exec.run\"]\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn empty_allow_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = []\n",
        );
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn rule_count_over_the_cap_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        let mut text = String::new();
        for i in 0..=caps::MAX_RULES {
            text.push_str(&format!(
                "[[acl]]\nprincipal = \"user:u{i}\"\nallow = [\"exec.run\"]\n"
            ));
        }
        write_acl(dir.path(), &text);
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn patterns_per_rule_over_the_cap_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        let patterns: Vec<String> = (0..=caps::MAX_PATTERNS_PER_RULE)
            .map(|_| "\"exec.run\"".to_string())
            .collect();
        let text = format!(
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [{}]\n",
            patterns.join(", ")
        );
        write_acl(dir.path(), &text);
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn file_over_the_byte_cap_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        // Pad with a TOML comment line well past the byte cap; the file
        // is rejected on size before parsing ever looks at content.
        let mut text = String::new();
        while (text.len() as u64) <= caps::MAX_FILE_BYTES {
            text.push_str("# padding padding padding padding padding padding\n");
        }
        write_acl(dir.path(), &text);
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    #[test]
    fn file_at_exactly_the_byte_cap_loads() {
        // F2 boundary companion to `file_over_the_byte_cap_is_invalid`: a
        // file whose size is exactly `MAX_FILE_BYTES` must still load —
        // the bounded-read rewrite must not have shifted the boundary by
        // one in either direction.
        let dir = tempfile::tempdir().unwrap();
        let mut text = String::from("#");
        while (text.len() as u64) < caps::MAX_FILE_BYTES - 1 {
            text.push('x');
        }
        text.push('\n');
        assert_eq!(text.len() as u64, caps::MAX_FILE_BYTES);
        write_acl(dir.path(), &text);
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(
            matches!(load, PolicyLoad::Loaded(_)),
            "a file of exactly MAX_FILE_BYTES must load, got {}",
            kind(&load)
        );
    }

    /// F2 (M5 Step 2 adversarial review): the byte cap used to be
    /// enforced against `fs::metadata().len()` alone, then the file was
    /// read with an unbounded `read_to_string` — a path whose `stat` size
    /// doesn't predict its read size (a FIFO, a device node) defeated the
    /// cap entirely. A symlink to `/dev/zero` reproduces exactly that:
    /// `stat` reports 0 bytes, but reading never ends on its own. If the
    /// fix regressed to the old stat-only gate, this test would hang
    /// forever reading zeroes instead of returning `Invalid` — the
    /// `recv_timeout` turns that into a fast, deterministic test failure
    /// instead of an actual hang.
    #[test]
    #[cfg(unix)]
    fn byte_cap_bounds_the_read_not_just_the_stat() {
        let dir = tempfile::tempdir().unwrap();
        std::os::unix::fs::symlink("/dev/zero", dir.path().join("acl.toml")).unwrap();
        let paths = paths_with(dir.path());
        let (tx, rx) = std::sync::mpsc::channel();
        std::thread::spawn(move || {
            let _ = tx.send(PolicySource::load(&paths));
        });
        let load = rx.recv_timeout(std::time::Duration::from_secs(10)).expect(
            "PolicySource::load must return promptly instead of reading /dev/zero \
                 unboundedly",
        );
        assert!(
            matches!(load, PolicyLoad::Invalid(_)),
            "over-cap content behind a stat-lying path must be Invalid, got {}",
            kind(&load)
        );
    }

    #[test]
    fn principal_over_the_length_cap_is_invalid() {
        let dir = tempfile::tempdir().unwrap();
        let long = "a".repeat(caps::MAX_PRINCIPAL_LEN + 1);
        let text = format!("[[acl]]\nprincipal = \"user:{long}\"\nallow = [\"exec.run\"]\n");
        write_acl(dir.path(), &text);
        let load = PolicySource::load(&paths_with(dir.path()));
        assert!(matches!(load, PolicyLoad::Invalid(_)));
    }

    // ---------------------------------------------------------------
    // F6(b): the three principal shapes `docs/CLI.md` §6.15 mandates.
    // ---------------------------------------------------------------

    #[test]
    fn each_valid_principal_shape_loads() {
        for principal in [
            "user:dave",
            "device:laptop",
            "fp:sha256:AAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        ] {
            let dir = tempfile::tempdir().unwrap();
            let text = format!("[[acl]]\nprincipal = \"{principal}\"\nallow = [\"exec.run\"]\n");
            write_acl(dir.path(), &text);
            let load = PolicySource::load(&paths_with(dir.path()));
            assert!(
                matches!(load, PolicyLoad::Loaded(_)),
                "{principal:?} is a valid shape and must load, got {}",
                kind(&load)
            );
        }
    }

    #[test]
    fn nonsense_principal_shapes_are_now_invalid() {
        // F6(b) REVERSES the pre-fix behavior (any string loaded
        // silently, "l6_loader_accepts_arbitrary_nonsense_principals_
        // silently"-class): a principal that can never match any real
        // `Principal::to_string()` output is now a load-time
        // `CONFIG_ERROR`, not a permanently-inert rule.
        for principal in ["hello world", "*", "dave", "USER:dave", "user:", "fp:"] {
            let dir = tempfile::tempdir().unwrap();
            let text = format!("[[acl]]\nprincipal = \"{principal}\"\nallow = [\"exec.run\"]\n");
            write_acl(dir.path(), &text);
            let load = PolicySource::load(&paths_with(dir.path()));
            assert!(
                matches!(load, PolicyLoad::Invalid(_)),
                "{principal:?} has no valid principal shape and must be Invalid, got {}",
                kind(&load)
            );
        }
    }

    // ---------------------------------------------------------------
    // F1: the Invalid message must never dump acl.toml source content,
    // and must always be a single line.
    // ---------------------------------------------------------------

    fn invalid_message(dir: &std::path::Path) -> String {
        match PolicySource::load(&paths_with(dir)) {
            PolicyLoad::Invalid(err) => err.message,
            other => panic!("expected Invalid, got {}", kind(&other)),
        }
    }

    fn kind(load: &PolicyLoad) -> &'static str {
        match load {
            PolicyLoad::Loaded(_) => "Loaded",
            PolicyLoad::Missing => "Missing",
            PolicyLoad::Invalid(_) => "Invalid",
        }
    }

    #[test]
    fn invalid_message_does_not_echo_acl_toml_source_content() {
        let dir = tempfile::tempdir().unwrap();
        // The syntax error sits on the same line as the sentinel, so the
        // old `toml::de::Error::to_string()`-verbatim message rendered
        // this exact line, principal included.
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"fp:sha256:SUPERSECRETPINVALUE\nallow = [\"exec.run\"]\n",
        );
        let msg = invalid_message(dir.path());
        assert!(
            !msg.contains("SUPERSECRETPINVALUE"),
            "CONFIG_ERROR message echoes acl.toml source content: {msg:?}"
        );
        assert!(
            !msg.contains('\n'),
            "CONFIG_ERROR message must be single-line: {msg:?}"
        );
    }

    #[test]
    fn invalid_messages_are_always_single_line() {
        // A sweep across every distinct way `parse`/`parse_rule` can
        // fail, including the three grammar-token echoes that F1
        // deliberately keeps (unknown action pattern/auth_path/scope) —
        // those echo a bounded, single-line-escaped grammar token, never
        // raw multi-line acl.toml source.
        let bad_files = [
            "this is not [ valid toml",
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"bogus.action\"]\n",
            "[[acl]]\nprincipal = \"user:dave\"\nauth_path = \"bogus\"\nallow = [\"exec.run\"]\n",
            "[[acl]]\nprincipal = \"user:dave\"\nscope = \"bogus\"\nallow = [\"exec.run\"]\n",
            "[[acl]]\nprincipal = \"\"\nallow = [\"exec.run\"]\n",
            "[[acl]]\nprincipal = \"nonsense\"\nallow = [\"exec.run\"]\n",
            "[[acl]]\nprincipal = \"user:dave\"\nallow = []\n",
        ];
        for text in bad_files {
            let dir = tempfile::tempdir().unwrap();
            write_acl(dir.path(), text);
            let msg = invalid_message(dir.path());
            assert!(
                !msg.contains('\n'),
                "Invalid message for {text:?} is not single-line: {msg:?}"
            );
        }
    }

    // ---------------------------------------------------------------
    // F9: pin that the two `tracing::warn!` diagnostics (always-denied
    // named action, F1 comment above `parse_rule`; zero rules loaded,
    // F7) actually fire, on the right target, with structural fields
    // only — not just that the code compiles a warn! call nobody ever
    // observes firing. A minimal hand-rolled `Subscriber` is enough
    // (`tracing`, unlike `tracing-subscriber`, is already an ordinary
    // dependency of this crate); no new dev-dependency is pulled in.
    // ---------------------------------------------------------------
    mod capture {
        use std::sync::{Arc, Mutex};

        use tracing::field::{Field, Visit};

        #[derive(Default)]
        pub(super) struct Sink {
            pub(super) events: Mutex<Vec<(String, String)>>, // (target, rendered fields)
        }

        struct Rec(String);
        impl Visit for Rec {
            fn record_debug(&mut self, field: &Field, value: &dyn std::fmt::Debug) {
                self.0.push_str(&format!("{}={:?} ", field.name(), value));
            }
        }

        pub(super) struct Sub(pub(super) Arc<Sink>);
        impl tracing::Subscriber for Sub {
            fn enabled(&self, _: &tracing::Metadata<'_>) -> bool {
                true
            }
            fn new_span(&self, _: &tracing::span::Attributes<'_>) -> tracing::Id {
                tracing::Id::from_u64(1)
            }
            fn record(&self, _: &tracing::Id, _: &tracing::span::Record<'_>) {}
            fn record_follows_from(&self, _: &tracing::Id, _: &tracing::Id) {}
            fn event(&self, event: &tracing::Event<'_>) {
                let mut rec = Rec(String::new());
                event.record(&mut rec);
                self.0
                    .events
                    .lock()
                    .unwrap()
                    .push((event.metadata().target().to_string(), rec.0));
            }
            fn enter(&self, _: &tracing::Id) {}
            fn exit(&self, _: &tracing::Id) {}
        }
    }

    fn capture_qsh_acl_events(text: &str) -> (PolicyLoad, Vec<(String, String)>) {
        use std::sync::Arc;
        let dir = tempfile::tempdir().unwrap();
        write_acl(dir.path(), text);
        let sink = Arc::new(capture::Sink::default());
        let sub = capture::Sub(sink.clone());
        let load =
            tracing::subscriber::with_default(sub, || PolicySource::load(&paths_with(dir.path())));
        let events = sink
            .events
            .lock()
            .unwrap()
            .iter()
            .filter(|(target, _)| target == "qsh::acl")
            .cloned()
            .collect();
        (load, events)
    }

    #[test]
    fn always_denied_named_action_warns_with_structural_fields_only() {
        let (load, events) = capture_qsh_acl_events(
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"forward.socks\", \"file.read\"]\n",
        );
        assert!(matches!(load, PolicyLoad::Loaded(_)));
        assert_eq!(
            events.len(),
            2,
            "one warning per exactly-named always-denied action, got {events:?}"
        );
        for (_, fields) in &events {
            assert!(fields.contains("rule="), "{fields}");
            assert!(fields.contains("action="), "{fields}");
            // Structural only — never the operator's own text.
            assert!(!fields.contains("user:dave"), "{fields}");
        }
    }

    #[test]
    fn wildcard_covering_an_always_denied_action_emits_no_warning() {
        let (load, events) = capture_qsh_acl_events(
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"forward.*\", \"file.*\"]\n",
        );
        assert!(matches!(load, PolicyLoad::Loaded(_)));
        assert!(
            events.is_empty(),
            "only exact always-denied action names warn, not the wildcards that cover them: {events:?}"
        );
    }

    #[test]
    fn zero_rules_loaded_warns() {
        for text in [
            "# no rules yet\n",
            "acl = []\n",
            "[[acls]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\n",
        ] {
            let (load, events) = capture_qsh_acl_events(text);
            let policy = load.as_loaded().expect("must still load");
            assert!(policy.rules.is_empty());
            assert_eq!(events.len(), 1, "{text:?} -> {events:?}");
            // No content beyond the fixed message — F7's warning carries
            // no operator-supplied text at all.
            assert!(!events[0].1.contains("dave"), "{events:?}");
        }
    }

    #[test]
    fn nonzero_rules_loaded_does_not_warn_about_zero_rules() {
        let (load, events) =
            capture_qsh_acl_events("[[acl]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\n");
        assert!(matches!(load, PolicyLoad::Loaded(_)));
        assert!(events.is_empty(), "{events:?}");
    }

    // ---------------------------------------------------------------
    // M5 Step 6 owed test (6): the group-/world-writable warning
    // (`warn_if_group_or_world_writable`) — non-fatal, fires once, never
    // on an owner-only file. Unix-only: the check itself is `#[cfg(unix)]`.
    // ---------------------------------------------------------------

    #[test]
    #[cfg(unix)]
    fn world_writable_acl_toml_loads_but_warns_once() {
        // F7 (`PLAN.md` M5 Step 6 PR 6a adversarial ④): table-driven over
        // the mode matrix so the group-writable bit *alone* is pinned, not
        // just the world-writable case — a mutation narrowing the mask
        // from `& 0o022` to `& 0o002` (other-write only) would still catch
        // 0o666/0o602 (both other-writable) but must be caught here by
        // 0o660 (group-writable, NOT other-writable), which the narrowed
        // mask would wrongly wave through as silent.
        use std::os::unix::fs::PermissionsExt;
        let cases: &[(u32, bool)] = &[
            (0o666, true),  // group- and world-writable
            (0o660, true),  // group-writable only
            (0o602, true),  // world-writable only
            (0o600, false), // owner-only: no warning
        ];
        for &(mode, should_warn) in cases {
            let dir = tempfile::tempdir().unwrap();
            write_acl(
                dir.path(),
                "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\n",
            );
            std::fs::set_permissions(
                dir.path().join("acl.toml"),
                std::fs::Permissions::from_mode(mode),
            )
            .unwrap();
            let sink = std::sync::Arc::new(capture::Sink::default());
            let sub = capture::Sub(sink.clone());
            let load = tracing::subscriber::with_default(sub, || {
                PolicySource::load(&paths_with(dir.path()))
            });
            assert!(
                load.as_loaded().is_some(),
                "{mode:03o}: a group-/world-writable file still loads — warning, not a deny"
            );
            let events: Vec<_> = sink
                .events
                .lock()
                .unwrap()
                .iter()
                .filter(|(target, _)| target == "qsh::acl")
                .cloned()
                .collect();
            if should_warn {
                assert_eq!(
                    events.len(),
                    1,
                    "{mode:03o}: exactly one warning, got {events:?}"
                );
                assert!(events[0].1.contains("mode="), "{mode:03o}: {events:?}");
                assert!(events[0].1.contains("path="), "{mode:03o}: {events:?}");
            } else {
                assert!(
                    events.is_empty(),
                    "{mode:03o}: must stay silent, got {events:?}"
                );
            }
        }
    }

    #[test]
    #[cfg(unix)]
    fn owner_only_acl_toml_does_not_warn() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\n",
        );
        std::fs::set_permissions(
            dir.path().join("acl.toml"),
            std::fs::Permissions::from_mode(0o600),
        )
        .unwrap();
        let sink = std::sync::Arc::new(capture::Sink::default());
        let sub = capture::Sub(sink.clone());
        let load =
            tracing::subscriber::with_default(sub, || PolicySource::load(&paths_with(dir.path())));
        assert!(load.as_loaded().is_some());
        let events: Vec<_> = sink
            .events
            .lock()
            .unwrap()
            .iter()
            .filter(|(target, _)| target == "qsh::acl")
            .cloned()
            .collect();
        assert!(events.is_empty(), "0600 must stay silent: {events:?}");
    }

    // ---------------------------------------------------------------
    // `load_or_deny` / `StartupDiagnostic` — the production wiring itself.
    // ---------------------------------------------------------------

    #[test]
    fn load_or_deny_on_missing_file_denies_and_names_the_missing_code() {
        let dir = tempfile::tempdir().unwrap();
        let (authorizer, diag) = load_or_deny(&paths_with(dir.path()));
        let verdict = authorizer.check(
            &Principal::Device("laptop".into()),
            AuthPath::Pin,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Deny);
        let diag = diag.expect("a missing acl.toml must produce a diagnostic");
        assert_eq!(diag.code, ACL_POLICY_MISSING_CODE);
        assert_eq!(diag.path, paths_with(dir.path()).acl_file());
        assert!(diag.detail.is_none());
        let rendered = diag.render();
        assert!(rendered.contains(ACL_POLICY_MISSING_CODE));
        assert!(rendered.contains(ErrorCode::ConfigError.as_str()));
        assert!(rendered.contains("[[acl]]"));
        // The other half of the F4 L6 gate (`acl_docs.rs` pins the docs to
        // these consts): pin `render()` itself to them too, so the banner
        // cannot silently stop emitting a fragment the docs still quote
        // verbatim as its wording.
        for fragment in [
            ACL_STARTUP_HEADLINE,
            ACL_STARTUP_DENIED_CLAUSE,
            ACL_STARTUP_NO_AUTOGEN,
            ACL_STARTUP_CHECK_HINT,
        ] {
            assert!(
                rendered.contains(fragment),
                "render() must emit {fragment:?} (docs quote it as the banner's wording)"
            );
        }
    }

    #[test]
    fn load_or_deny_on_invalid_file_denies_and_carries_a_content_free_detail() {
        // F3 (`PLAN.md` M5 Step 6 PR 6a adversarial ①): table-driven over
        // every distinct way `PolicySource::load_path` can produce
        // `PolicyLoad::Invalid`, not just the TOML-syntax shape this test
        // used to cover alone. `SENTINEL` sits inside a full raw source
        // line of the file for every shape, so "the raw line never
        // survives into `render()`" is actually exercised per-shape
        // instead of assumed to generalize from one.
        const SENTINEL: &str = "SUPERSECRETPINVALUE0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";

        struct Case {
            name: &'static str,
            text: String,
            /// The exact raw source line (no trailing `\n`) the sentinel
            /// sits on — must never appear anywhere in `detail`/`render()`,
            /// for every shape without exception.
            raw_line: String,
            /// `Some(token)` for the three Step 2 grammar-token carve-outs
            /// (this file's F1 doc comment, `parse_rule`'s three
            /// `unknown ... {other:?}`/`{pattern:?}` arms): `detail` DOES
            /// echo `token` verbatim, but bounded (<=128 bytes) and
            /// single-line. `None` for every other shape, where nothing
            /// from the file survives into `detail` at all.
            grammar_token: Option<String>,
        }

        let over_length_pattern = SENTINEL.repeat(3);
        assert!(
            over_length_pattern.len() > caps::MAX_PATTERN_LEN,
            "test setup: the over-length pattern must actually exceed the cap"
        );
        let unknown_action = format!("{SENTINEL}.bogus");

        let cases = [
            Case {
                name: "toml syntax error",
                text: format!(
                    "[[acl]]\nprincipal = \"fp:sha256:{SENTINEL}\nallow = [\"exec.run\"]\n"
                ),
                raw_line: format!("principal = \"fp:sha256:{SENTINEL}"),
                grammar_token: None,
            },
            Case {
                name: "unknown action pattern",
                text: format!(
                    "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"{unknown_action}\"]\n"
                ),
                raw_line: format!("allow = [\"{unknown_action}\"]"),
                grammar_token: Some(unknown_action.clone()),
            },
            Case {
                name: "unknown auth_path",
                text: format!(
                    "[[acl]]\nprincipal = \"user:dave\"\nauth_path = \"{SENTINEL}\"\n\
                     allow = [\"exec.run\"]\n"
                ),
                raw_line: format!("auth_path = \"{SENTINEL}\""),
                grammar_token: Some(SENTINEL.to_string()),
            },
            Case {
                name: "unknown scope",
                text: format!(
                    "[[acl]]\nprincipal = \"user:dave\"\nscope = \"{SENTINEL}\"\n\
                     allow = [\"exec.run\"]\n"
                ),
                raw_line: format!("scope = \"{SENTINEL}\""),
                grammar_token: Some(SENTINEL.to_string()),
            },
            Case {
                name: "over-length action pattern",
                text: format!(
                    "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"{over_length_pattern}\"]\n"
                ),
                raw_line: format!("allow = [\"{over_length_pattern}\"]"),
                grammar_token: None,
            },
            Case {
                name: "serde type error",
                text: format!(
                    "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\n\
                     # {SENTINEL}\nauth_path = 12345\n"
                ),
                raw_line: format!("# {SENTINEL}"),
                grammar_token: None,
            },
            Case {
                name: "missing field",
                text: format!("[[acl]]\nprincipal = \"user:{SENTINEL}\"\n"),
                raw_line: format!("principal = \"user:{SENTINEL}\""),
                grammar_token: None,
            },
        ];

        for case in cases {
            let dir = tempfile::tempdir().unwrap();
            write_acl(dir.path(), &case.text);
            let (authorizer, diag) = load_or_deny(&paths_with(dir.path()));
            let verdict = authorizer.check(
                &Principal::Device("laptop".into()),
                AuthPath::Pin,
                Action::ExecRun,
                ResourceRef::unowned("exec"),
            );
            assert_eq!(
                verdict.decision,
                Decision::Deny,
                "{}: an invalid acl.toml must deny",
                case.name
            );
            let diag = diag.unwrap_or_else(|| {
                panic!(
                    "{}: an invalid acl.toml must produce a diagnostic",
                    case.name
                )
            });
            assert_eq!(diag.code, ACL_POLICY_INVALID_CODE, "{}", case.name);
            let detail = diag
                .detail
                .as_ref()
                .unwrap_or_else(|| panic!("{}: Invalid always carries a detail", case.name));
            let rendered = diag.render();

            assert!(
                !detail.contains(&case.raw_line) && !rendered.contains(&case.raw_line),
                "{}: raw acl.toml source line leaked into the diagnostic: {detail:?}",
                case.name
            );

            match &case.grammar_token {
                None => {
                    assert!(
                        !detail.contains(SENTINEL) && !rendered.contains(SENTINEL),
                        "{}: diagnostic must be content-free, got detail={detail:?}",
                        case.name
                    );
                }
                Some(token) => {
                    assert!(
                        detail.contains(token.as_str()),
                        "{}: the documented grammar-token carve-out must still echo the \
                         token, got detail={detail:?}",
                        case.name
                    );
                    assert!(
                        token.len() <= caps::MAX_PATTERN_LEN,
                        "{}: test setup: grammar token must fit the documented <=128-byte \
                         bound",
                        case.name
                    );
                    assert!(
                        !detail.contains('\n'),
                        "{}: the grammar-token carve-out must stay single-line: {detail:?}",
                        case.name
                    );
                }
            }
        }
    }

    #[test]
    fn load_or_deny_on_loaded_policy_has_no_diagnostic_and_evaluates_rules() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"device:laptop\"\nallow = [\"exec.run\"]\n",
        );
        let (authorizer, diag) = load_or_deny(&paths_with(dir.path()));
        assert!(diag.is_none());
        let verdict = authorizer.check(
            &Principal::Device("laptop".into()),
            AuthPath::Pin,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Allow);
        let verdict = authorizer.check(
            &Principal::Device("laptop".into()),
            AuthPath::Pin,
            Action::SessionOpen,
            ResourceRef::unowned("s1"),
        );
        assert_eq!(verdict.decision, Decision::Deny);
    }

    // ---------------------------------------------------------------
    // M5 Step 6 owed test (4): the CA-path round trip through the real
    // `load_or_deny` pipeline — a rule with no `auth_path` (defaults to
    // `pin`) never grants a CA-authenticated peer anything, and an
    // explicit `auth_path = "ca"` rule does. No CA issuance harness exists
    // at the real-binary level yet (private CA is M6 scope,
    // `crate::trust`'s own module doc), so this exercises the same
    // `AuthPath` distinction `crates/qsh-cli/tests/acl_enforcement.rs`'s
    // owed tests (1)/(2)/(3)/(5) exercise for the pin path, through the
    // one function production actually calls (`load_or_deny`), not just
    // `Policy::decide` against a hand-built `Policy` (`policy.rs`'s own
    // `auth_path`-sensitive tests already cover that half in isolation).
    // ---------------------------------------------------------------

    #[test]
    fn load_or_deny_ca_path_round_trip_default_denies_explicit_ca_allows() {
        let dir = tempfile::tempdir().unwrap();
        write_acl(
            dir.path(),
            "[[acl]]\nprincipal = \"user:dave\"\nallow = [\"exec.run\"]\n\n\
             [[acl]]\nprincipal = \"user:carol\"\nauth_path = \"ca\"\nallow = [\"exec.run\"]\n",
        );
        let (authorizer, diag) = load_or_deny(&paths_with(dir.path()));
        assert!(diag.is_none());

        // `dave`'s rule has no `auth_path` — defaults to `pin` (F6(b)'s own
        // discipline) — so a CA-authenticated `dave` is denied even though
        // the principal string matches a real rule.
        let verdict = authorizer.check(
            &Principal::User("dave".into()),
            AuthPath::Ca,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Deny, "no implicit CA grant");
        // The same principal, pinned, is allowed — the rule it omitted
        // `auth_path` for.
        let verdict = authorizer.check(
            &Principal::User("dave".into()),
            AuthPath::Pin,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Allow);

        // `carol`'s rule explicitly names `auth_path = "ca"`: a
        // CA-authenticated `carol` is allowed, but a *pinned* `carol` is
        // not — the rule never claimed to cover that path.
        let verdict = authorizer.check(
            &Principal::User("carol".into()),
            AuthPath::Ca,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Allow);
        let verdict = authorizer.check(
            &Principal::User("carol".into()),
            AuthPath::Pin,
            Action::ExecRun,
            ResourceRef::unowned("exec"),
        );
        assert_eq!(verdict.decision, Decision::Deny, "the rule never named pin");
    }

    #[test]
    fn minimal_policy_example_fills_in_actual_pinned_peer_names() {
        let dir = tempfile::tempdir().unwrap();
        let mut trust = crate::trust::TrustStore::default();
        trust.add_peer(
            "laptop",
            None,
            qsh_transport::Fingerprint::of_spki_der(b"k"),
            "2026-01-01T00:00:00Z".to_string(),
        );
        trust.save(&dir.path().join("trust.toml")).unwrap();
        let example = minimal_policy_example(&paths_with(dir.path()));
        assert!(example.contains("device:laptop"), "{example:?}");
    }
}
